spring:
  application:
    name: merchandise-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/sipin-sales?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        hikari:
          connection-timeout: 5000
          maximum-pool-size: 25
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
      # 设置正常关闭超时时间，如正常关闭应用程序时，给lettuce连接处池100ms关闭时间，超过则强行关闭
      shutdown-timeout: 100ms
    # 连接超时时间（毫秒）
    timeout: 10000ms

  flyway:
    enabled: true
    ignore-missing-migrations: true
    out-of-order: true
    validate-on-migrate: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  quartz:
    properties:
      org.quartz.scheduler.instanceId: sku-sync
      org.quartz.scheduler.instanceName: sku-sync
      org.quartz.scheduler.threadName: sku-sync
      org.quartz.threadPool.threadCount: 2

  zipkin:
    base-url: http://localhost:8006

mybatis-plus:
  mapper-locations: classpath:/cn/sipin/sales/cloud/merchandise/service/mapper/xml/*Mapper.xml
  global-config:
      id-type: 0
      field-strategy: 2
      db-column-underline: true
      refresh-mapper: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true



server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# ========================
# = Third Party
# ========================
# sipin test
thirdparty:
  material-sync:
    serverUrl: http://localhost:8080/materials-stock
    enable: false
    interval: 5
    delay: 0
  material-group-sync:
    serverUrl: http://localhost:8080/materials-group
    enable: false
    interval: 5
    delay: 0

logging:
  level:
    cn.sipin.sales.cloud.merchandise.service:
      INFO

